name: 'DevHost rsync'
description: 'Perform a rsync of a file or a folder to the DevHost."'
inputs:
  hostname:
    description: 'Hostname of the DevHost server.'
    required: true
  user:
    description: 'User of the DevHost server.'
    required: true
  ssh_key:
    description: 'SSH key for the user of the DevHost server.'
    required: true
  local_path:
    description: 'Local path of the file or folder to sync.'
    required: true
  remote_path:
    description: 'Remote path of the file or folder to sync.'
    required: true
  download:
    description: 'Perform download instead of upload.'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/action.sh
      shell: bash
      env:
        INPUT_DEV_HOST_HOSTNAME: ${{ inputs.hostname }}
        INPUT_DEV_HOST_USER: ${{ inputs.user }}
        INPUT_DEV_HOST_SSH_KEY: ${{ inputs.ssh_key }}
        INPUT_LOCAL_PATH: ${{ inputs.local_path }}
        INPUT_REMOTE_PATH: ${{ inputs.remote_path }}
        INPUT_DOWNLOAD: ${{ inputs.download }}
