name: 'DevHost run-script'
description: 'Upload a shell script to and run it on the DevHost.'
inputs:
  hostname:
    description: 'Hostname of the DevHost server.'
    required: true
  user:
    description: 'User of the DevHost server.'
    required: true
  ssh_key:
    description: 'SSH key for the user of the DevHost server.'
    required: true
  script_path:
    description: 'Local path of the script file.'
    required: true
  script_shell:
    description: 'Shell to run the script, default to bash.'
    required: false
    default: bash
  script_args:
    description: 'Arguments passed to the script.'
    required: false
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo "INPUT_REMOTE_PATH=/tmp/action-$RANDOM-$(basename "${{ inputs.script_path }}")" >> $GITHUB_ENV

    - shell: bash
      run: ${{ github.action_path }}/../rsync/action.sh
      env:
        INPUT_DEV_HOST_HOSTNAME: ${{ inputs.hostname }}
        INPUT_DEV_HOST_USER: ${{ inputs.user }}
        INPUT_DEV_HOST_SSH_KEY: ${{ inputs.ssh_key }}
        INPUT_LOCAL_PATH: ${{ inputs.script_path }}

    - shell: bash
      run: ${{ github.action_path }}/../exec/action.sh
      env:
        INPUT_DEV_HOST_HOSTNAME: ${{ inputs.hostname }}
        INPUT_DEV_HOST_USER: ${{ inputs.user }}
        INPUT_DEV_HOST_SSH_KEY: ${{ inputs.ssh_key }}
        INPUT_COMMAND: ${{ inputs.script_shell }} ${{ env.INPUT_REMOTE_PATH }} -- ${{ inputs.script_args }}
