name: CI Master

on:
  push:
    paths:
      - 'actions/rsync/**'
      - '.github/workflows/test-actions-rsync.yml'
jobs:
  test:
    name: Test rsync action

    runs-on: ubuntu-latest

    steps:
      - name: Checkout local code
        uses: actions/checkout@v2

      - name: Show contexts
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}

      - name: Test rsync action locally
        uses: ./actions/rsync
        with:
          hostname: ${{ secrets.DEV_HOST_HOSTNAME }}
          user: ${{ secrets.DEV_HOST_USER }}
          ssh_key: ${{ secrets.DEV_HOST_SSH_KEY }}
          local_path: actions
          remote_path: ~/tmp/
