name: 'DevHost rsync'
description: 'Perform a rsync of a file or a folder to the DevHost.'
inputs:
  hostname:
    description: 'Hostname of the DevHost server.'
    required: true
  user:
    description: 'User of the DevHost server.'
    required: true
  ssh_key:
    description: 'SSH key for the user of the DevHost server.'
    required: true
  command:
    description: 'The command to be executed on the DevHost.'
    required: true
outputs:
  command_output: # id of output
    description: 'The first-line output of the command.'
    value: ${{ steps.main.outputs.command_output }}
runs:
  using: 'composite'
  steps:
    - id: main
      shell: bash
      run: |
        OUTPUT=$( ${{ github.action_path }}/action.sh )
        echo "::set-output name=command_output::${OUTPUT}"
      env:
        INPUT_DEV_HOST_HOSTNAME: ${{ inputs.hostname }}
        INPUT_DEV_HOST_USER: ${{ inputs.user }}
        INPUT_DEV_HOST_SSH_KEY: ${{ inputs.ssh_key }}
        INPUT_COMMAND: ${{ inputs.command }}
